// <auto-generated />
using GameListWebApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GameListWebApi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250729023319_databaseIdChange")]
    partial class databaseIdChange
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GameListWebApi.Models.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("games");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Adventure game extremely hard full of challenge",
                            Title = "Elden Ring"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Beautiful game with a rich story",
                            Title = "Stellar blade"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Adventure game and puzzle",
                            Title = "The Legend Of Zelda"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Game of robot trying to be humain",
                            Title = "Nier Automata"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Mecha game action and fight",
                            Title = "Armored Core V"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Game of war shooting game",
                            Title = "Battlefield 3"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
